buildDrafts: false
buildFuture: false
baseURL: http://jamesmalcolm.me.s3-website-ap-southeast-2.amazonaws.com/

deployment:
  targets:
    - name: staging
      URL: 's3://jamesmalcolm.me?region=ap-southeast-2'
  matchers:
    - pattern: ^.+\.(js|css|png|jpg|gif|svg|ttf)$
      cacheControl: 'max-age=630720000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true