baseURL = "https://jamesmalcolm.me/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Call me James"
theme                    = "james"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics        = "UA-158965144-1"                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    homepage             = "home"
    footerText           = "James Malcolm. Copyright 2020."

# Metadata for Open Graph and Twitter
    description          = "Blog by James Malcolm exploring Machine Learning, business and stock analysis."               # Max 160 characters show in search results
    title                = "Call me James"

[[params.mainMenu]]
    link = "/posts"
    text = "posts"

#[[params.mainMenu]]
#    link = "/gallery"
#    text = "gallery"

#[[params.mainMenu]]
#    link = "/portfolio"
#    text = "portfolio"

[[params.mainMenu]]
    link = "/about"
    text = "who am i?"

[imaging]
    quality = 75