baseURL: 'https://jamesmalcolm.me/'
googleAnalytics: UA-158965144-1
buildDrafts: false
buildFuture: false

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

deployment:
  targets:
    - name: jamesmalcolm.me
      URL: 's3://jamesmalcolm.me?region=ap-southeast-2'
  matchers:
    - pattern: ^.+\.(js|css|png|jpg|gif|svg|ttf)$
      cacheControl: 'max-age=630720000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
