baseURL: 'https://jamesmalcolm.me/'
canonifyURLs: true
googleAnalytics: G-V3TJ1V7BX1
buildDrafts: false
buildFuture: false

disqusShortname: jamesmalcolm

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  comments: true
